var x = 3;
var y = 1.1;
console.log(x + y);
console.log(x * y);
console.log((x+y)*(x-y));
var z = 9;
console.log(Math.sqrt(z));
console.log(Math.abs(y/x));
var res = x * y;
console.log(res.toFixed(2));